# Generated by Django 4.2.2 on 2023-06-17 18:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'Comunidad',
            },
        ),
        migrations.CreateModel(
            name='DuenoMascota',
            fields=[
                ('id_dueno_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.IntegerField(blank=True)),
                ('fk_comunidad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.comunidad')),
                ('fk_customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dueño de mascota',
                'verbose_name_plural': 'Dueños de mascotas',
                'db_table': 'DuenoMascota',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_vencimiento', models.DateField(blank=True)),
                ('total', models.IntegerField()),
                ('tipo', models.IntegerField(blank=True)),
                ('forma_pago', models.CharField(blank=True, max_length=100)),
                ('fk_dueno_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.duenomascota')),
            ],
            options={
                'verbose_name': 'Factura de la compra',
                'verbose_name_plural': 'Facturas de las compras',
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Paseador',
            fields=[
                ('id_paseador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('servicios', models.CharField(max_length=200)),
                ('fk_comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad')),
                ('fk_customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paseador de perros',
                'verbose_name_plural': 'Paseadores de perros',
                'db_table': 'Paseador',
            },
        ),
        migrations.CreateModel(
            name='PeluqueriaCanina',
            fields=[
                ('id_peluqueria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_peluqueria', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('productos', models.CharField(blank=True, max_length=200)),
                ('servicios', models.CharField(blank=True, max_length=200)),
                ('fk_comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad')),
                ('fk_customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.factura')),
            ],
            options={
                'verbose_name': 'Peluqueria canina',
                'verbose_name_plural': 'Peluquerias caninas',
                'db_table': 'PeluqueriaCanina',
            },
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id_posteo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=5000)),
                ('imagen', models.ImageField(upload_to='img-posteo')),
                ('url', models.URLField(null=True)),
                ('comentario', models.TextField(max_length=3000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fk_comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad')),
            ],
            options={
                'verbose_name': 'Posteo en comunidad',
                'verbose_name_plural': 'Posteos en comunidad',
                'db_table': 'Posteo',
            },
        ),
        migrations.CreateModel(
            name='RegistroMascota',
            fields=[
                ('id_registro_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacimiento', models.DateField(blank=True)),
                ('especie_animal', models.CharField(max_length=200)),
                ('raza', models.CharField(blank=True, max_length=200)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('patologia', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Registro de la mascota',
                'verbose_name_plural': 'Registro de las mascotas',
                'db_table': 'RegistroMascota',
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_veterinaria', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('productos', models.CharField(blank=True, max_length=200)),
                ('servicios', models.CharField(blank=True, max_length=200)),
                ('fk_comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.posteo')),
                ('fk_customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinaria',
                'verbose_name_plural': 'Veterinarias',
                'db_table': 'Veterinaria',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=150)),
                ('a_domicilio', models.BooleanField(default=False)),
                ('cercanas', models.BooleanField(default=False)),
                ('de_guardia', models.BooleanField(default=False)),
                ('fk_dueno_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.duenomascota')),
                ('fk_paseador', models.ManyToManyField(to='appMascotas.paseador')),
                ('fk_peluqueria', models.ManyToManyField(to='appMascotas.peluqueriacanina')),
                ('fk_veterinaria', models.ManyToManyField(to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fk_dueno_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.duenomascota')),
                ('fk_paseador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.paseador')),
                ('fk_peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.peluqueriacanina')),
                ('fk_veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Reserva del servicio',
                'verbose_name_plural': 'Reservas de los servicios',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_barra', models.IntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('precio', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
                ('id_fabricante', models.IntegerField()),
                ('stock_disponible', models.IntegerField()),
                ('imagen', models.ImageField(default='img-producto/default.jpg', upload_to='img-producto')),
                ('fk_veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Proucto',
            },
        ),
        migrations.AddField(
            model_name='paseador',
            name='fk_posteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.posteo'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('especie_animal', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('peso_recomendado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad_fisica', models.CharField(max_length=255)),
                ('clima_recomendado', models.CharField(max_length=200)),
                ('alimentacion', models.TextField(max_length=1000)),
                ('esperanza_vida', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('patologia', models.CharField(max_length=200)),
                ('vacunas', models.CharField(max_length=255)),
                ('fk_dueno_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.duenomascota')),
                ('fk_paseador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.paseador')),
                ('fk_peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.peluqueriacanina')),
                ('fk_registro_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.registromascota')),
                ('fk_veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('contenido', models.TextField(null=True)),
                ('imagen', models.BooleanField(null=True)),
                ('imagen_url', models.URLField(null=True)),
                ('comentarios', models.TextField(max_length=1000, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('fk_comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad')),
                ('fk_dueno_mascota', models.ManyToManyField(to='appMascotas.duenomascota')),
                ('fk_paseador', models.ManyToManyField(to='appMascotas.paseador')),
                ('fk_peluqueria', models.ManyToManyField(to='appMascotas.peluqueriacanina')),
                ('fk_veterinaria', models.ManyToManyField(to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Grupo de la comunidad',
                'verbose_name_plural': 'Grupos de la comunidad',
                'db_table': 'Grupo',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_peluquerias',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.peluqueriacanina'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.veterinaria'),
        ),
        migrations.AddField(
            model_name='duenomascota',
            name='fk_paseador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.paseador'),
        ),
        migrations.AddField(
            model_name='duenomascota',
            name='fk_peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.peluqueriacanina'),
        ),
        migrations.AddField(
            model_name='duenomascota',
            name='fk_veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMascotas.veterinaria'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id_avatar', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='avatars/default.jpg', upload_to='avatars')),
                ('fk_dueno_mascota', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.duenomascota')),
                ('fk_paseador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.paseador')),
                ('fk_peluqueria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.peluqueriacanina')),
                ('fk_veterinaria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.veterinaria')),
            ],
            options={
                'verbose_name': 'Avatar del usuario',
                'verbose_name_plural': 'Avatars de los usuarios',
                'db_table': 'Avatar',
            },
        ),
    ]
